import { PORT_UNLIMITED, type NodeDefinition } from "./definition.js";

/**
 * Built-in node catalog. Add a new type here first, then follow
 * docs → Extend → Adding a built-in node.
 */
export const BUILTIN_NODE_DEFINITIONS: readonly NodeDefinition[] = [
  {
    id: "prompt",
    label: "Prompt",
    glyph: "✎",
    wireColor: "var(--wire-prompt)",
    textSource: true,
    ports: { in: 0, out: PORT_UNLIMITED },
    emitsText: true,
    mutable: true,
    palette: {
      label: "Prompt",
      glyph: "✎",
      hint: "free text · wire into an agent",
      iconBg: "var(--accent)",
      iconFg: "#0a0a0b",
      order: 10,
    },
    wireMenu: {
      label: "Prompt",
      glyph: "✎",
      hint: "free text · wire into an agent",
      iconBg: "var(--accent)",
      order: 10,
    },
  },
  {
    id: "output",
    label: "Output",
    glyph: "⇤",
    wireColor: "var(--wire-output)",
    textSource: true,
    textSink: true,
    ports: { in: 1, out: PORT_UNLIMITED },
    requiresInput: true,
    executesOnRun: true,
    mutable: true,
    palette: {
      label: "Output",
      glyph: "⇤",
      hint: "last message of a session",
      iconBg: "var(--status-running)",
      order: 20,
    },
    wireMenu: {
      label: "Output",
      glyph: "⇤",
      hint: "last message of a session",
      iconBg: "var(--status-running)",
      order: 20,
    },
  },
  {
    id: "prompt-convert",
    label: "Text → Prompt",
    glyph: "⇄",
    wireColor: "var(--wire-prompt-convert)",
    textSource: true,
    textSink: true,
    ports: { in: 1, out: 1 },
    requiresInput: true,
    emitsText: true,
    executesOnRun: true,
    mutable: true,
    palette: {
      label: "Text → Prompt",
      glyph: "⇄",
      hint: "template incoming text",
      iconBg: "var(--wire-prompt-convert)",
      iconFg: "#3a2f08",
      order: 30,
    },
    wireMenu: {
      label: "Text → Prompt",
      glyph: "⇄",
      hint: "template incoming text",
      iconBg: "var(--wire-prompt-convert)",
      order: 30,
    },
  },
  {
    id: "delay",
    label: "Delay",
    glyph: "◷",
    wireColor: "var(--wire-delay)",
    textSource: true,
    textSink: true,
    ports: { in: 1, out: 1 },
    requiresInput: true,
    emitsText: true,
    executesOnRun: true,
    mutable: true,
    palette: {
      label: "Delay",
      glyph: "◷",
      hint: "wall-clock pause · no agent",
      iconBg: "var(--border)",
      order: 40,
    },
    wireMenu: {
      label: "Delay",
      glyph: "◷",
      hint: "wall-clock pause · no agent",
      iconBg: "var(--border)",
      order: 40,
    },
  },
  {
    id: "data",
    label: "Data",
    glyph: "◇",
    wireColor: "var(--wire-data)",
    textSource: true,
    textSink: true,
    ports: { in: 1, out: 1 },
    // constant on the card is enough — inbound wire is optional (overrides value)
    requiresInput: false,
    emitsText: true,
    executesOnRun: true,
    mutable: true,
    palette: {
      label: "Data",
      glyph: "◇",
      hint: "typed value · string · int · float · bool · json",
      iconBg: "var(--wire-data)",
      iconFg: "#0a0a0b",
      order: 35,
    },
    wireMenu: {
      label: "Data",
      glyph: "◇",
      hint: "typed value · string · int · float · bool · json",
      iconBg: "var(--wire-data)",
      order: 35,
    },
  },
  {
    id: "approval",
    label: "Approval gate",
    glyph: "✓",
    wireColor: "var(--wire-approval)",
    textSource: true,
    textSink: true,
    ports: { in: 1, out: 1 },
    requiresInput: true,
    emitsText: true,
    executesOnRun: true,
    mutable: true,
    palette: {
      label: "Approval gate",
      glyph: "✓",
      hint: "pause the run for review",
      iconBg: "var(--status-waiting)",
      iconFg: "#3a2f08",
      order: 50,
    },
    wireMenu: {
      label: "Approval gate",
      glyph: "✓",
      hint: "pause the run for review",
      iconBg: "var(--status-waiting)",
      order: 50,
    },
  },
  {
    id: "live-handoff",
    label: "Live handoff",
    glyph: "⇄",
    wireColor: "var(--wire-live-handoff)",
    textSource: true,
    textSink: true,
    ports: { in: 1, out: 1 },
    emitsText: true,
    executesOnRun: true,
    mutable: true,
    palette: {
      label: "Live handoff",
      glyph: "⇄",
      hint: "chat until Ready · distill · continue",
      iconBg: "var(--lane-session)",
      iconFg: "#0b1c30",
      order: 60,
    },
    wireMenu: {
      label: "Live handoff",
      glyph: "⇄",
      hint: "chat until Ready · distill · continue",
      iconBg: "var(--lane-session)",
      order: 60,
    },
  },
  {
    id: "wait-idle",
    label: "Wait for idle",
    glyph: "◌",
    wireColor: "var(--wire-wait-idle)",
    textSource: true,
    textSink: true,
    ports: { in: 1, out: 1 },
    requiresInput: true,
    emitsText: true,
    executesOnRun: true,
    mutable: true,
    palette: {
      label: "Wait for idle",
      glyph: "◌",
      hint: "park until session is not generating",
      iconBg: "var(--lane-session)",
      iconFg: "#0b1c30",
      order: 65,
    },
    wireMenu: {
      label: "Wait for idle",
      glyph: "◌",
      hint: "park until session is not generating",
      iconBg: "var(--lane-session)",
      order: 65,
    },
  },
  {
    id: "iterator",
    label: "Iterator",
    glyph: "∀",
    wireColor: "var(--wire-iterator)",
    textSource: true,
    textSink: true,
    ports: { in: 1, out: 1 },
    requiresInput: true,
    emitsText: true,
    executesOnRun: true,
    mutable: true,
    palette: {
      label: "Iterator",
      glyph: "∀",
      hint: "run once per item · serial or parallel map",
      iconBg: "var(--lane-session)",
      iconFg: "#0b1c30",
      order: 70,
    },
    wireMenu: {
      label: "Iterator",
      glyph: "∀",
      hint: "run once per item · serial or parallel map",
      iconBg: "var(--lane-session)",
      order: 70,
    },
  },
  {
    id: "knot",
    label: "Merge",
    glyph: "⋈",
    wireColor: "var(--wire-knot)",
    textSource: true,
    textSink: true,
    ports: { in: PORT_UNLIMITED, out: 1 },
    requiresInput: true,
    emitsText: true,
    executesOnRun: true,
    mutable: true,
    palette: {
      label: "Merge",
      glyph: "⋈",
      hint: "combine inbound wires (concat / vote / synthesize)",
      iconBg: "var(--accent)",
      iconFg: "#0a0a0b",
      order: 80,
    },
    wireMenu: {
      label: "Merge",
      glyph: "⋈",
      hint: "combine inbound wires (concat / vote / synthesize)",
      iconBg: "var(--accent)",
      order: 80,
    },
  },
  {
    id: "tripwire",
    label: "Circuit breaker",
    glyph: "‡",
    wireColor: "var(--wire-tripwire)",
    textSource: true,
    textSink: true,
    ports: { in: 1, out: 1 },
    requiresInput: true,
    emitsText: true,
    executesOnRun: true,
    mutable: true,
    palette: {
      label: "Circuit breaker",
      glyph: "‡",
      hint: "spend / tokens / time / content / retry fuse",
      iconBg: "var(--status-waiting)",
      iconFg: "#0a0a0b",
      order: 90,
    },
    wireMenu: {
      label: "Circuit breaker",
      glyph: "‡",
      hint: "spend / tokens / time / content / retry fuse",
      iconBg: "var(--status-waiting)",
      order: 90,
    },
  },
  {
    id: "judge",
    label: "Judge",
    glyph: "?",
    wireColor: "var(--wire-judge)",
    textSource: true,
    textSink: true,
    ports: { in: 1, out: 1 },
    requiresInput: true,
    emitsText: true,
    executesOnRun: true,
    mutable: true,
    palette: {
      label: "Judge",
      glyph: "?",
      hint: "route by regex / contains · pass · fail · unsure",
      iconBg: "var(--status-waiting)",
      iconFg: "#0a0a0b",
      order: 95,
    },
    wireMenu: {
      label: "Judge",
      glyph: "?",
      hint: "route by regex / contains · pass · fail · unsure",
      iconBg: "var(--status-waiting)",
      order: 95,
    },
  },
  {
    id: "until",
    label: "Until",
    glyph: "↻",
    wireColor: "var(--wire-until)",
    textSource: true,
    textSink: true,
    ports: { in: 1, out: 1 },
    requiresInput: true,
    emitsText: true,
    executesOnRun: true,
    mutable: true,
    palette: {
      label: "Until",
      glyph: "↻",
      hint: "counted re-entry · max N · reenter / exhausted",
      iconBg: "var(--status-waiting)",
      iconFg: "#0a0a0b",
      order: 96,
    },
    wireMenu: {
      label: "Until",
      glyph: "↻",
      hint: "counted re-entry · max N · reenter / exhausted",
      iconBg: "var(--status-waiting)",
      order: 96,
    },
  },
  {
    id: "group",
    label: "Group frame",
    glyph: "▦",
    wireColor: "var(--wire-group)",
    ports: { in: PORT_UNLIMITED, out: PORT_UNLIMITED },
    skipExec: true,
    palette: {
      label: "Group frame",
      glyph: "▦",
      hint: "visual grouping · drag moves members",
      iconBg: "var(--panel-bg-raised)",
      iconFg: "var(--text-dim)",
      order: 100,
    },
    wireMenu: {
      label: "Group frame",
      glyph: "▦",
      hint: "visual grouping · drag moves members",
      iconBg: "var(--panel-bg-raised)",
      order: 100,
    },
  },
  {
    id: "note",
    label: "Note",
    glyph: "✎",
    wireColor: "var(--accent)",
    ports: { in: 0, out: 0 },
    skipExec: true,
    palette: {
      label: "Note",
      glyph: "✎",
      hint: "sticky annotation · never runs",
      iconBg: "rgba(207, 169, 60, 0.25)",
      iconFg: "var(--context)",
      order: 110,
    },
    wireMenu: {
      label: "Note",
      glyph: "✎",
      hint: "sticky annotation · never runs",
      iconBg: "rgba(207, 169, 60, 0.25)",
      order: 110,
    },
  },
  {
    id: "agent-def",
    label: "Agent",
    glyph: "⟨/⟩",
    wireColor: "provider",
    textSource: true,
    textSink: true,
    structuralTo: ["session", "context"],
    ports: { in: PORT_UNLIMITED, out: PORT_UNLIMITED },
    requiresInput: true,
    emitsText: true,
    executesOnRun: true,
    mutable: true,
    palette: false,
    wireMenu: false,
  },
  {
    id: "session",
    label: "Session",
    glyph: "❯",
    wireColor: "provider",
    textSource: true,
    textSink: true,
    structuralTo: ["context", "subagent-run"],
    ports: { in: PORT_UNLIMITED, out: PORT_UNLIMITED },
    emitsText: true,
    executesOnRun: "session-if-wired",
    mutable: true,
    palette: false,
    wireMenu: false,
  },
  {
    id: "subagent-run",
    label: "Subagent run",
    glyph: "❯",
    wireColor: "provider",
    textSource: true,
    structuralTo: ["context"],
    ports: { in: 1, out: PORT_UNLIMITED },
    emitsText: true,
    skipInDetached: true,
    palette: false,
    wireMenu: false,
  },
  {
    id: "context",
    label: "Context",
    glyph: "❝",
    wireColor: "var(--wire-context)",
    textSource: true,
    structuralTo: ["session"],
    forbidTextTo: ["output"],
    ports: { in: 1, out: PORT_UNLIMITED },
    emitsText: true,
    executesOnRun: true,
    mutable: true,
    palette: false,
    wireMenu: [
      {
        label: "Distilled summary",
        glyph: "❝",
        hint: "distill a session into a brief",
        iconBg: "var(--context)",
        contextKind: "distilled-summary",
        order: 200,
      },
      {
        label: "Transcript excerpt",
        glyph: "❝",
        hint: "raw conversation excerpt",
        iconBg: "var(--context)",
        contextKind: "transcript-excerpt",
        order: 210,
      },
      {
        label: "Files / artifacts",
        glyph: "▤",
        hint: "paths and artifacts from a session",
        iconBg: "var(--context)",
        contextKind: "files",
        order: 220,
      },
    ],
  },
  {
    id: "skill",
    label: "Skill",
    glyph: "✦",
    wireColor: "var(--wire-skill)",
    textSource: true,
    textSink: true,
    // inject→output still discouraged via graph lint; invoke may wire to output
    ports: { in: 1, out: PORT_UNLIMITED },
    emitsText: true,
    executesOnRun: true,
    palette: false,
    wireMenu: false,
  },
  {
    id: "rules",
    label: "Rules",
    glyph: "▤",
    wireColor: "var(--wire-rules)",
    textSource: true,
    forbidTextTo: ["output"],
    ports: { in: 0, out: PORT_UNLIMITED },
    emitsText: true,
    executesOnRun: true,
    palette: false,
    wireMenu: false,
  },
  {
    id: "custom",
    label: "Custom",
    glyph: "◇",
    wireColor: "var(--wire-custom)",
    textSource: true,
    textSink: true,
    ports: { in: 1, out: 1 },
    requiresInput: true,
    emitsText: true,
    executesOnRun: true,
    mutable: true,
    palette: false,
    wireMenu: false,
  },
  {
    id: "mcp-tool",
    label: "MCP tool",
    glyph: "◈",
    wireColor: "var(--wire-mcp)",
    textSource: true,
    textSink: true,
    ports: { in: 1, out: 1 },
    requiresInput: false,
    emitsText: true,
    executesOnRun: true,
    mutable: true,
    palette: {
      label: "MCP tool",
      glyph: "◈",
      hint: "call a tool on a discovered MCP server",
      iconBg: "var(--wire-mcp)",
      iconFg: "#0a0a0b",
      order: 55,
    },
    wireMenu: {
      label: "MCP tool",
      glyph: "◈",
      hint: "call a tool on a discovered MCP server",
      iconBg: "var(--wire-mcp)",
      order: 55,
    },
  },
];
